environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: mingw64

build_script:
  - PATH C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%

    #Install deps
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-cmake make mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5 mingw-w64-x86_64-glew mingw-w64-x86_64-glm mingw-w64-x86_64-assimp mingw-w64-x86_64-bullet mingw-w64-x86_64-ninja"

    #Build
  - |
    bash -lc "
    mkdir build
    cd build
    cmake -G 'MSYS Makefiles' -DCMAKE_INSTALL_PREFIX='install' -DCMAKE_BUILD_TYPE='RelWithDebInfo' -G 'Ninja' ..
    ninja
    ninja install
    "

