sudo: required
language: cpp

os:
  - linux
  - osx

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t ws2 .; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --name ws2 ws2; fi
  - mkdir -p $TRAVIS_BUILD_DIR/ws2install/deploy

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=clang; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=clang++; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_PREFIX_PATH="/usr/local/opt/qt/lib/cmake"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade || true; fi #OR with true as the python update will yell about the linking
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake qt5 glew glm assimp bullet ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd build; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX="install" -G "Ninja" ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ninja install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r install installnodeps; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ninja package; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil attach smblevelworkshop2*-Darwin.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir installwithdeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r /Volumes/smblevelworkshop2*-Darwin/ws2editor.app installwithdeps/ws2editor.app; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir installwithdeps/ws2editor.app/Contents/MacOS; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd installwithdeps/ws2editor.app/Contents/MacOS; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s ../Resources/bin/* .; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ../../..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt ws2editor.app; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ..; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r installnodeps $TRAVIS_BUILD_DIR/ws2install/smblevelworkshop2-nodeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -r installwithdeps $TRAVIS_BUILD_DIR/ws2install/smblevelworkshop2-withdeps; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd $TRAVIS_BUILD_DIR; fi

before_deploy:
  - sed -ie "s/|||COMMIT|||/${TRAVIS_COMMIT}/g" .bintray-descriptor.json
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -ie "s/|||ARCH|||/linux-x86_64/g" .bintray-descriptor.json; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -ie "s/|||ARCH|||/macos-x86_64/g" .bintray-descriptor.json; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker cp ws2:/app/build/installnodeps $TRAVIS_BUILD_DIR/ws2install/smblevelworkshop2-nodeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker cp ws2:/app/build/installwithdeps $TRAVIS_BUILD_DIR/ws2install/smblevelworkshop2-withdeps; fi

  - cd $TRAVIS_BUILD_DIR/ws2install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar zcvf deploy/smblevelworkshop2-bleedingedge-nodeps.tar.gz --owner=0 --group=0 smblevelworkshop2-nodeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar zcvf deploy/smblevelworkshop2-bleedingedge-withdeps.tar.gz --owner=0 --group=0 smblevelworkshop2-withdeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar zcvf deploy/smblevelworkshop2-bleedingedge-nodeps.tar.gz smblevelworkshop2-nodeps; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar zcvf deploy/smblevelworkshop2-bleedingedge-withdeps.tar.gz smblevelworkshop2-withdeps; fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip-cleanup: true
  provider: bintray
  file: ".bintray-descriptor.json"
  user: craftedcart
  key:
    secure: FVAAYOTu2AYuR+J7veZ+bpgv7ZO6uqdWE6sCVAyhLgUZWCU1hphbJbIsf0UHTci0lIivTunnnmUKYLBi9K6iFLVE9Genb5Bxd1a8ZXxhFE3bU/rWlz6y6fVPNFiqOWDgJCnqkTLpnaZslP+xADsbwsKKemikPp9M+W9IM2E/TGWz2j/E6m12fvyOS8QpbycPqVsNjS46UfWfzN2eOYtxlxhooIpfUIiOzNE96wJwAq7DHTW/3pBSuN7mviLymUeD7rsg4FkaqzGoEe2BPV3NUd4qNrk/4epeW3AnPZyvzkECrPlNwgrrU0szmVfDTSGT14P1UdlWXWBMdrD+ty9mggYeXbe6/cdpMynjmRI/UO0XjNU7R7u9TCQDpnAQ79Lks82+KD5kp+npUoREUd1ljkjX9j78YB6+H3+HqM7rz4HzTMnnzTrIU6tdtrzK6eJ/ouGezIEautnPfQ4f9s0qdy7R0wIo+zdP5aeb1Y+M1gKP6OxC2/OQy52Jc2ce0Gg0dCBhx/jD2/tO9xiTCIwdGkhm9SrlcQ/jDEvAvUO9kcPHs1BZ7kdCuLBBU7wyzQ+0RIzAt2oIhRNW+kBCOJXfBGr/EDliutPT1bK5WDEYnXsNlm7N77VUV8cjAR3gD3VRbg5Nr/VEAfYOmAc4E4kKxeP043Dl7OgOEe1fGy+eJ6w=
